name: Docker

on: [ workflow_dispatch ]

env:
  DOCKER_REPO: severalnines

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKER_REPO }}
          password: ${{ secrets.DH_PASS }}

      - name: Set up Go
        uses: actions/setup-go@v5

      - name: Build
        run: make build

      - name: Create container
        run: make docker DOCKER_IMAGE_TAG=${{ github.run_number }}

      - name: Tag container
        run: make docker-tag-latest DOCKER_IMAGE_TAG=${{ github.run_number }}

      - name: Publish container
        run: make docker-publish DOCKER_IMAGE_TAG=${{ github.run_number }}
